<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>AbittiAgent.Server</RootNamespace>
    <ApplicationIcon>..\..\assets\AbittiAgent.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AbittiAgent.Shared\AbittiAgent.Shared.csproj" />
  </ItemGroup>
</Project>
